databases:
  - name: maho_DB
    databaseName: maho_DB
    user: maho
    region: singapore

services:
  - type: web
    name: maho
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: maho_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false